"""greetings db

Revision ID: e684b846376c
Revises: 
Create Date: 2019-01-21 14:09:47.789119

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e684b846376c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('greetings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('language', sa.String(length=64), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_greetings'))
    )
    op.create_index(op.f('ix_greetings_language'), 'greetings', ['language'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_greetings_language'), table_name='greetings')
    op.drop_table('greetings')
    # ### end Alembic commands ###
